import '../globals.css'
import Link from "next/link"
import { getPages } from '@/sanity/sanity-utils';

export const metadata = {
  title: "Petow's Pantry",
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="">
        <header className="">
          <Link href="/" className="">KP</Link>
          <div className="">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="">{page.title}</Link>
            ))}

          </div>

        </header>
        <main className="">{children}</main>
      </body>
    </html>
  )
}